[target.x86_64-pc-windows-msvc]
linker = "lld-link"
rustflags = ["-C", "linker=lld-link", "-C", "link-args=/nodefaultlib /subsystem:native /entry:entry /base:0x133700000000 /filealign:0x1000 /fixed /nodefaultlib /align:4096 /debug:dwarf"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
