[package]
name = "mmu"
version = "0.1.0"
edition = "2021"

[dependencies]
cpu = { version = "0.1.0", path = "../cpu"}
serial = { version = "0.1.0", path = "../serial"}
ops = { version = "0.1.0", path = "../ops"}
