[target.i586-pc-windows-msvc]
linker = "lld-link"
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-args=/nodefaultlib"]

[target.x86_64-pc-windows-msvc]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
