[target.i586-pc-windows-msvc]
linker = "lld-link"
rustflags = ["-C", "link-args=/nodefaultlib /driver /subsystem:native /entry:entry /base:0x6e00 /filealign:0x1000 /fixed /align:1"]

[target.x86_64-pc-windows-msvc]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
